export const MENU_IDS = [
  'file',
  'file/create-new',
  'file/create-new/sprite',
  'file/create-new/map',
  'file/open',
  'file/open/sprite',
  'file/open/map',
  'file/save',
  'file/save-as',
  'file/import',
  'file/export',

  'edit',
  'edit/undo',
  'edit/redo',
  'edit/history',
  'edit/hot-keys',
  'edit/preferences',

  'view',
  'view/mode',
  'view/grid',
  'view/minimize',
  'view/show',

  'sprite',
  'sprite/create-new',
  'sprite/load',
  'sprite/save',
  'sprite/duplicate',
  'sprite/resize',
  'sprite/crop',
  'sprite/rotate',
  'sprite/delete',

  'map',
  'map/create-new',
  'map/load',
  'map/save',
  'map/resize',
  'map/tile-size',

  'help',
  'help/documentation',
  'help/tutorial',
  'help/support',
  'help/report-a-bug',
  'help/about',
] as const;
